# Generated by Django 3.0.2 on 2020-09-18 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='postcode',
            field=models.CharField(default=3000, max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$')]),
            preserve_default=False,
        ),
    ]
