# Generated by Django 3.0.2 on 2020-09-20 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='waste_volume',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
            preserve_default=False,
        ),
    ]
