# Generated by Django 3.0.2 on 2020-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default='2005-10-10 20:11:59'),
            preserve_default=False,
        ),
    ]
