# Generated by Django 3.0.2 on 2020-08-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='area_name',
        ),
    ]
