# Generated by Django 3.0.2 on 2020-10-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201011_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='reported_at',
            field=models.DateTimeField(),
        ),
    ]
