# Generated by Django 3.0.2 on 2020-09-20 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_assignment_waste_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='waste_volume',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
