# Generated by Django 3.0.2 on 2020-10-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201011_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='dmg_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
