# Generated by Django 3.0.2 on 2020-09-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200921_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='colcen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
