# Generated by Django 3.0.2 on 2020-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201013_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='severity',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='dmg_type',
            field=models.CharField(default='broken handle', max_length=100),
            preserve_default=False,
        ),
    ]
