# Generated by Django 3.0.2 on 2020-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
