# Generated by Django 3.0.2 on 2020-10-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201014_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
