# Generated by Django 3.0.2 on 2020-09-21 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200921_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_num',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='colcen_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{4}$')]),
        ),
    ]
