# Generated by Django 3.0.2 on 2020-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200921_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bins_collected',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
