# Generated by Django 3.0.2 on 2020-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_employee_bins_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
