# Generated by Django 3.0.2 on 2020-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201014_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
