# Generated by Django 3.0.2 on 2020-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_assignment_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
