# Generated by Django 3.0.2 on 2020-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200922_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='on_shift',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
