# Generated by Django 3.0.2 on 2020-10-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201015_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagereport',
            old_name='date_solved',
            new_name='datetime_solved',
        ),
    ]
