# Generated by Django 3.0.2 on 2020-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_employee_emp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
