# Generated by Django 3.0.2 on 2020-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_assignment_total_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='emp_firstname',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_lastname',
            field=models.CharField(default='Doe', max_length=100),
            preserve_default=False,
        ),
    ]
