# Generated by Django 3.0.2 on 2020-10-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201016_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_done',
        ),
    ]
