# Generated by Django 3.0.2 on 2020-10-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_assignment_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='total_distance',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='last_cleared_datetime',
        ),
    ]
